[package]
name = "make-it-rusty"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
http = "~0.2"
roux = "~2.2.5"
tokio = { version = "1.25.0", features = ["full"] }